###############################################
# Modify all parameters related to servoing here
###############################################
use_gazebo: false

## Properties of incoming commands
command_in_type: "unitless"
scale:
  linear: 0.3
  rotational: 0.6
  joint: 0.5

## Properties of outgoing commands
publish_period: 0.034
low_latency_mode: false
low_pass_filter_coeff: 2.0

# What type of topic does your robot driver expect?
command_out_type: trajectory_msgs/JointTrajectory

# What to publish?
publish_joint_positions: true
publish_joint_velocities: true
publish_joint_accelerations: false

## Plugins for smoothing outgoing commands
smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

## MoveIt properties
move_group_name: manipulator
planning_frame: base_link
robot_link_command_frame: base_link
ee_frame_name: end_effector_link

## Stopping behaviour
incoming_command_timeout: 0.1
num_outgoing_halt_msgs_to_publish: 4

## Configure handling of singularities and joint limits
lower_singularity_threshold: 30.0  # Increased: BioIK handles singularities better
hard_stop_singularity_threshold: 50.0  # Increased: Rely on BioIK
joint_limit_margin: 0.2  # Reduced: Allow joint_3 (3.0 rad)
leaving_singularity_threshold_multiplier: 2.0

## Topic names
cartesian_command_in_topic: ~/delta_twist_cmds
joint_command_in_topic: ~/delta_joint_cmds
joint_topic: ~/joint_states
status_topic: ~/status
command_out_topic: ~/joint_trajectory

## Collision checking for the entire robot body
check_collisions: true
collision_check_rate: 10.0
self_collision_proximity_threshold: 0.05
scene_collision_proximity_threshold: 0.06
